/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as NetworkOptimizationRouteImport } from './routes/network-optimization'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as QuantumOptimizerRouteImport } from './routes/quantum-optimizer'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as ResponseNetworkRouteImport } from './routes/response-network'
import { Route as RiskMapRouteImport } from './routes/risk-map'
import { Route as ScenariosRouteImport } from './routes/scenarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkOptimizationRoute = NetworkOptimizationRouteImport.update({
  id: '/network-optimization',
  path: '/network-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumOptimizerRoute = QuantumOptimizerRouteImport.update({
  id: '/quantum-optimizer',
  path: '/quantum-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseNetworkRoute = ResponseNetworkRouteImport.update({
  id: '/response-network',
  path: '/response-network',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMapRoute = RiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/forecast': typeof ForecastRoute
  '/network-optimization': typeof NetworkOptimizationRoute
  '/overview': typeof OverviewRoute
  '/quantum-optimizer': typeof QuantumOptimizerRoute
  '/response': typeof ResponseRoute
  '/response-network': typeof ResponseNetworkRoute
  '/risk-map': typeof RiskMapRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/forecast': typeof ForecastRoute
  '/network-optimization': typeof NetworkOptimizationRoute
  '/overview': typeof OverviewRoute
  '/quantum-optimizer': typeof QuantumOptimizerRoute
  '/response': typeof ResponseRoute
  '/response-network': typeof ResponseNetworkRoute
  '/risk-map': typeof RiskMapRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/forecast': typeof ForecastRoute
  '/network-optimization': typeof NetworkOptimizationRoute
  '/overview': typeof OverviewRoute
  '/quantum-optimizer': typeof QuantumOptimizerRoute
  '/response': typeof ResponseRoute
  '/response-network': typeof ResponseNetworkRoute
  '/risk-map': typeof RiskMapRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/forecast'
    | '/network-optimization'
    | '/overview'
    | '/quantum-optimizer'
    | '/response'
    | '/response-network'
    | '/risk-map'
    | '/scenarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/forecast'
    | '/network-optimization'
    | '/overview'
    | '/quantum-optimizer'
    | '/response'
    | '/response-network'
    | '/risk-map'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/forecast'
    | '/network-optimization'
    | '/overview'
    | '/quantum-optimizer'
    | '/response'
    | '/response-network'
    | '/risk-map'
    | '/scenarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ForecastRoute: typeof ForecastRoute
  NetworkOptimizationRoute: typeof NetworkOptimizationRoute
  OverviewRoute: typeof OverviewRoute
  QuantumOptimizerRoute: typeof QuantumOptimizerRoute
  ResponseRoute: typeof ResponseRoute
  ResponseNetworkRoute: typeof ResponseNetworkRoute
  RiskMapRoute: typeof RiskMapRoute
  ScenariosRoute: typeof ScenariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-optimization': {
      id: '/network-optimization'
      path: '/network-optimization'
      fullPath: '/network-optimization'
      preLoaderRoute: typeof NetworkOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-optimizer': {
      id: '/quantum-optimizer'
      path: '/quantum-optimizer'
      fullPath: '/quantum-optimizer'
      preLoaderRoute: typeof QuantumOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response-network': {
      id: '/response-network'
      path: '/response-network'
      fullPath: '/response-network'
      preLoaderRoute: typeof ResponseNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-map': {
      id: '/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof RiskMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ForecastRoute: ForecastRoute,
  NetworkOptimizationRoute: NetworkOptimizationRoute,
  OverviewRoute: OverviewRoute,
  QuantumOptimizerRoute: QuantumOptimizerRoute,
  ResponseRoute: ResponseRoute,
  ResponseNetworkRoute: ResponseNetworkRoute,
  RiskMapRoute: RiskMapRoute,
  ScenariosRoute: ScenariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
